export const SET_CITIES = "SET_CITIES";
export const FETCH_WETHER_REQUEST = "FETCH_WETHER_REQUEST";
export const FETCH_WETHER_SUCCESS = "FETCH_WETHER_SUCCESS";
export const FETCH_WETHER_FAILURE = "FETCH_WETHER_FAILURE";
export const FETCH_FIVE_DAYS_WETHER_SUCCESS = "FETCH_FIVE_DAYS_WETHER_SUCCESS";
